server:
  port : 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/citience'
    username: 'citience'
    password: 'citience'
    driverClassName: 'org.postgresql.Driver'

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'

springdoc:
  swagger-ui:
    path: '/api/documentation.html'

node:
  id: 'Philipp'
  identityPath: 'C:\Users\Philipp\Entwicklung\Java\citience\backend\src\main\resources'

network:
  reference: ''