server:
  port : 8080
spring:
  data:
    mongodb:
      database: "citience"

node:
  id: "Philipp"
  identityPath: 'C:\Users\Philipp\Entwicklung\Java\citience\backend\src\main\resources'

network:
  reference: ""